# Generated by Django 4.0.2 on 2022-04-08 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='fecha_actualiza',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='usu_actualiza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='usu_update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produccion',
            name='usu_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='usu_creation', to=settings.AUTH_USER_MODEL),
        )

    ]
