# Generated by Django 4.0.2 on 2022-04-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0003_remove_produccion_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desperdicios',
            options={'managed': True},
        ),
    ]
