# Generated by Django 4.0.2 on 2022-04-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0005_desperdicios_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desperdicios',
            name='fecha',
        ),
    ]
